// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: http.proto

package cn.chennan.server.proto;

public final class Http {
  private Http() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Point3fOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.chennan.server.proto.Point3f)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float x = 1;</code>
     * @return The x.
     */
    float getX();

    /**
     * <code>float y = 2;</code>
     * @return The y.
     */
    float getY();

    /**
     * <code>float z = 3;</code>
     * @return The z.
     */
    float getZ();
  }
  /**
   * Protobuf type {@code cn.chennan.server.proto.Point3f}
   */
  public  static final class Point3f extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.chennan.server.proto.Point3f)
      Point3fOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Point3f.newBuilder() to construct.
    private Point3f(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Point3f() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Point3f();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Point3f(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              x_ = input.readFloat();
              break;
            }
            case 21: {

              y_ = input.readFloat();
              break;
            }
            case 29: {

              z_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.chennan.server.proto.Http.internal_static_cn_chennan_server_proto_Point3f_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.chennan.server.proto.Http.internal_static_cn_chennan_server_proto_Point3f_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.chennan.server.proto.Http.Point3f.class, cn.chennan.server.proto.Http.Point3f.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private float x_;
    /**
     * <code>float x = 1;</code>
     * @return The x.
     */
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private float y_;
    /**
     * <code>float y = 2;</code>
     * @return The y.
     */
    public float getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private float z_;
    /**
     * <code>float z = 3;</code>
     * @return The z.
     */
    public float getZ() {
      return z_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0F) {
        output.writeFloat(1, x_);
      }
      if (y_ != 0F) {
        output.writeFloat(2, y_);
      }
      if (z_ != 0F) {
        output.writeFloat(3, z_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, x_);
      }
      if (y_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, y_);
      }
      if (z_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, z_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.chennan.server.proto.Http.Point3f)) {
        return super.equals(obj);
      }
      cn.chennan.server.proto.Http.Point3f other = (cn.chennan.server.proto.Http.Point3f) obj;

      if (java.lang.Float.floatToIntBits(getX())
          != java.lang.Float.floatToIntBits(
              other.getX())) return false;
      if (java.lang.Float.floatToIntBits(getY())
          != java.lang.Float.floatToIntBits(
              other.getY())) return false;
      if (java.lang.Float.floatToIntBits(getZ())
          != java.lang.Float.floatToIntBits(
              other.getZ())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getX());
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getY());
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getZ());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.chennan.server.proto.Http.Point3f parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.chennan.server.proto.Http.Point3f parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.chennan.server.proto.Http.Point3f parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.chennan.server.proto.Http.Point3f parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.chennan.server.proto.Http.Point3f parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.chennan.server.proto.Http.Point3f parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.chennan.server.proto.Http.Point3f parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.chennan.server.proto.Http.Point3f parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.chennan.server.proto.Http.Point3f parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.chennan.server.proto.Http.Point3f parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.chennan.server.proto.Http.Point3f parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.chennan.server.proto.Http.Point3f parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.chennan.server.proto.Http.Point3f prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.chennan.server.proto.Point3f}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.chennan.server.proto.Point3f)
        cn.chennan.server.proto.Http.Point3fOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.chennan.server.proto.Http.internal_static_cn_chennan_server_proto_Point3f_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.chennan.server.proto.Http.internal_static_cn_chennan_server_proto_Point3f_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.chennan.server.proto.Http.Point3f.class, cn.chennan.server.proto.Http.Point3f.Builder.class);
      }

      // Construct using cn.chennan.server.proto.Http.Point3f.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        x_ = 0F;

        y_ = 0F;

        z_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.chennan.server.proto.Http.internal_static_cn_chennan_server_proto_Point3f_descriptor;
      }

      @java.lang.Override
      public cn.chennan.server.proto.Http.Point3f getDefaultInstanceForType() {
        return cn.chennan.server.proto.Http.Point3f.getDefaultInstance();
      }

      @java.lang.Override
      public cn.chennan.server.proto.Http.Point3f build() {
        cn.chennan.server.proto.Http.Point3f result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.chennan.server.proto.Http.Point3f buildPartial() {
        cn.chennan.server.proto.Http.Point3f result = new cn.chennan.server.proto.Http.Point3f(this);
        result.x_ = x_;
        result.y_ = y_;
        result.z_ = z_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.chennan.server.proto.Http.Point3f) {
          return mergeFrom((cn.chennan.server.proto.Http.Point3f)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.chennan.server.proto.Http.Point3f other) {
        if (other == cn.chennan.server.proto.Http.Point3f.getDefaultInstance()) return this;
        if (other.getX() != 0F) {
          setX(other.getX());
        }
        if (other.getY() != 0F) {
          setY(other.getY());
        }
        if (other.getZ() != 0F) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.chennan.server.proto.Http.Point3f parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.chennan.server.proto.Http.Point3f) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float x_ ;
      /**
       * <code>float x = 1;</code>
       * @return The x.
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>float x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(float value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>float y = 2;</code>
       * @return The y.
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>float y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(float value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        
        y_ = 0F;
        onChanged();
        return this;
      }

      private float z_ ;
      /**
       * <code>float z = 3;</code>
       * @return The z.
       */
      public float getZ() {
        return z_;
      }
      /**
       * <code>float z = 3;</code>
       * @param value The z to set.
       * @return This builder for chaining.
       */
      public Builder setZ(float value) {
        
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float z = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearZ() {
        
        z_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.chennan.server.proto.Point3f)
    }

    // @@protoc_insertion_point(class_scope:cn.chennan.server.proto.Point3f)
    private static final cn.chennan.server.proto.Http.Point3f DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.chennan.server.proto.Http.Point3f();
    }

    public static cn.chennan.server.proto.Http.Point3f getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Point3f>
        PARSER = new com.google.protobuf.AbstractParser<Point3f>() {
      @java.lang.Override
      public Point3f parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Point3f(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Point3f> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Point3f> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.chennan.server.proto.Http.Point3f getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PointCloudOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.chennan.server.proto.PointCloud)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 total = 1;</code>
     * @return The total.
     */
    int getTotal();

    /**
     * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
     */
    java.util.List<cn.chennan.server.proto.Http.Point3f> 
        getMapPointsList();
    /**
     * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
     */
    cn.chennan.server.proto.Http.Point3f getMapPoints(int index);
    /**
     * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
     */
    int getMapPointsCount();
    /**
     * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
     */
    java.util.List<? extends cn.chennan.server.proto.Http.Point3fOrBuilder> 
        getMapPointsOrBuilderList();
    /**
     * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
     */
    cn.chennan.server.proto.Http.Point3fOrBuilder getMapPointsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code cn.chennan.server.proto.PointCloud}
   */
  public  static final class PointCloud extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.chennan.server.proto.PointCloud)
      PointCloudOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PointCloud.newBuilder() to construct.
    private PointCloud(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PointCloud() {
      mapPoints_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PointCloud();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PointCloud(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              total_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                mapPoints_ = new java.util.ArrayList<cn.chennan.server.proto.Http.Point3f>();
                mutable_bitField0_ |= 0x00000001;
              }
              mapPoints_.add(
                  input.readMessage(cn.chennan.server.proto.Http.Point3f.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          mapPoints_ = java.util.Collections.unmodifiableList(mapPoints_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.chennan.server.proto.Http.internal_static_cn_chennan_server_proto_PointCloud_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.chennan.server.proto.Http.internal_static_cn_chennan_server_proto_PointCloud_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.chennan.server.proto.Http.PointCloud.class, cn.chennan.server.proto.Http.PointCloud.Builder.class);
    }

    public static final int TOTAL_FIELD_NUMBER = 1;
    private int total_;
    /**
     * <code>int32 total = 1;</code>
     * @return The total.
     */
    public int getTotal() {
      return total_;
    }

    public static final int MAP_POINTS_FIELD_NUMBER = 2;
    private java.util.List<cn.chennan.server.proto.Http.Point3f> mapPoints_;
    /**
     * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
     */
    public java.util.List<cn.chennan.server.proto.Http.Point3f> getMapPointsList() {
      return mapPoints_;
    }
    /**
     * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
     */
    public java.util.List<? extends cn.chennan.server.proto.Http.Point3fOrBuilder> 
        getMapPointsOrBuilderList() {
      return mapPoints_;
    }
    /**
     * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
     */
    public int getMapPointsCount() {
      return mapPoints_.size();
    }
    /**
     * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
     */
    public cn.chennan.server.proto.Http.Point3f getMapPoints(int index) {
      return mapPoints_.get(index);
    }
    /**
     * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
     */
    public cn.chennan.server.proto.Http.Point3fOrBuilder getMapPointsOrBuilder(
        int index) {
      return mapPoints_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (total_ != 0) {
        output.writeInt32(1, total_);
      }
      for (int i = 0; i < mapPoints_.size(); i++) {
        output.writeMessage(2, mapPoints_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (total_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, total_);
      }
      for (int i = 0; i < mapPoints_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, mapPoints_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.chennan.server.proto.Http.PointCloud)) {
        return super.equals(obj);
      }
      cn.chennan.server.proto.Http.PointCloud other = (cn.chennan.server.proto.Http.PointCloud) obj;

      if (getTotal()
          != other.getTotal()) return false;
      if (!getMapPointsList()
          .equals(other.getMapPointsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOTAL_FIELD_NUMBER;
      hash = (53 * hash) + getTotal();
      if (getMapPointsCount() > 0) {
        hash = (37 * hash) + MAP_POINTS_FIELD_NUMBER;
        hash = (53 * hash) + getMapPointsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.chennan.server.proto.Http.PointCloud parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.chennan.server.proto.Http.PointCloud parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.chennan.server.proto.Http.PointCloud parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.chennan.server.proto.Http.PointCloud parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.chennan.server.proto.Http.PointCloud parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.chennan.server.proto.Http.PointCloud parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.chennan.server.proto.Http.PointCloud parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.chennan.server.proto.Http.PointCloud parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.chennan.server.proto.Http.PointCloud parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.chennan.server.proto.Http.PointCloud parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.chennan.server.proto.Http.PointCloud parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.chennan.server.proto.Http.PointCloud parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.chennan.server.proto.Http.PointCloud prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.chennan.server.proto.PointCloud}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.chennan.server.proto.PointCloud)
        cn.chennan.server.proto.Http.PointCloudOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.chennan.server.proto.Http.internal_static_cn_chennan_server_proto_PointCloud_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.chennan.server.proto.Http.internal_static_cn_chennan_server_proto_PointCloud_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.chennan.server.proto.Http.PointCloud.class, cn.chennan.server.proto.Http.PointCloud.Builder.class);
      }

      // Construct using cn.chennan.server.proto.Http.PointCloud.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMapPointsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        total_ = 0;

        if (mapPointsBuilder_ == null) {
          mapPoints_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          mapPointsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.chennan.server.proto.Http.internal_static_cn_chennan_server_proto_PointCloud_descriptor;
      }

      @java.lang.Override
      public cn.chennan.server.proto.Http.PointCloud getDefaultInstanceForType() {
        return cn.chennan.server.proto.Http.PointCloud.getDefaultInstance();
      }

      @java.lang.Override
      public cn.chennan.server.proto.Http.PointCloud build() {
        cn.chennan.server.proto.Http.PointCloud result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.chennan.server.proto.Http.PointCloud buildPartial() {
        cn.chennan.server.proto.Http.PointCloud result = new cn.chennan.server.proto.Http.PointCloud(this);
        int from_bitField0_ = bitField0_;
        result.total_ = total_;
        if (mapPointsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            mapPoints_ = java.util.Collections.unmodifiableList(mapPoints_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.mapPoints_ = mapPoints_;
        } else {
          result.mapPoints_ = mapPointsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.chennan.server.proto.Http.PointCloud) {
          return mergeFrom((cn.chennan.server.proto.Http.PointCloud)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.chennan.server.proto.Http.PointCloud other) {
        if (other == cn.chennan.server.proto.Http.PointCloud.getDefaultInstance()) return this;
        if (other.getTotal() != 0) {
          setTotal(other.getTotal());
        }
        if (mapPointsBuilder_ == null) {
          if (!other.mapPoints_.isEmpty()) {
            if (mapPoints_.isEmpty()) {
              mapPoints_ = other.mapPoints_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMapPointsIsMutable();
              mapPoints_.addAll(other.mapPoints_);
            }
            onChanged();
          }
        } else {
          if (!other.mapPoints_.isEmpty()) {
            if (mapPointsBuilder_.isEmpty()) {
              mapPointsBuilder_.dispose();
              mapPointsBuilder_ = null;
              mapPoints_ = other.mapPoints_;
              bitField0_ = (bitField0_ & ~0x00000001);
              mapPointsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMapPointsFieldBuilder() : null;
            } else {
              mapPointsBuilder_.addAllMessages(other.mapPoints_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.chennan.server.proto.Http.PointCloud parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.chennan.server.proto.Http.PointCloud) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int total_ ;
      /**
       * <code>int32 total = 1;</code>
       * @return The total.
       */
      public int getTotal() {
        return total_;
      }
      /**
       * <code>int32 total = 1;</code>
       * @param value The total to set.
       * @return This builder for chaining.
       */
      public Builder setTotal(int value) {
        
        total_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 total = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotal() {
        
        total_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<cn.chennan.server.proto.Http.Point3f> mapPoints_ =
        java.util.Collections.emptyList();
      private void ensureMapPointsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          mapPoints_ = new java.util.ArrayList<cn.chennan.server.proto.Http.Point3f>(mapPoints_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.chennan.server.proto.Http.Point3f, cn.chennan.server.proto.Http.Point3f.Builder, cn.chennan.server.proto.Http.Point3fOrBuilder> mapPointsBuilder_;

      /**
       * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
       */
      public java.util.List<cn.chennan.server.proto.Http.Point3f> getMapPointsList() {
        if (mapPointsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(mapPoints_);
        } else {
          return mapPointsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
       */
      public int getMapPointsCount() {
        if (mapPointsBuilder_ == null) {
          return mapPoints_.size();
        } else {
          return mapPointsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
       */
      public cn.chennan.server.proto.Http.Point3f getMapPoints(int index) {
        if (mapPointsBuilder_ == null) {
          return mapPoints_.get(index);
        } else {
          return mapPointsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
       */
      public Builder setMapPoints(
          int index, cn.chennan.server.proto.Http.Point3f value) {
        if (mapPointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMapPointsIsMutable();
          mapPoints_.set(index, value);
          onChanged();
        } else {
          mapPointsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
       */
      public Builder setMapPoints(
          int index, cn.chennan.server.proto.Http.Point3f.Builder builderForValue) {
        if (mapPointsBuilder_ == null) {
          ensureMapPointsIsMutable();
          mapPoints_.set(index, builderForValue.build());
          onChanged();
        } else {
          mapPointsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
       */
      public Builder addMapPoints(cn.chennan.server.proto.Http.Point3f value) {
        if (mapPointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMapPointsIsMutable();
          mapPoints_.add(value);
          onChanged();
        } else {
          mapPointsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
       */
      public Builder addMapPoints(
          int index, cn.chennan.server.proto.Http.Point3f value) {
        if (mapPointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMapPointsIsMutable();
          mapPoints_.add(index, value);
          onChanged();
        } else {
          mapPointsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
       */
      public Builder addMapPoints(
          cn.chennan.server.proto.Http.Point3f.Builder builderForValue) {
        if (mapPointsBuilder_ == null) {
          ensureMapPointsIsMutable();
          mapPoints_.add(builderForValue.build());
          onChanged();
        } else {
          mapPointsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
       */
      public Builder addMapPoints(
          int index, cn.chennan.server.proto.Http.Point3f.Builder builderForValue) {
        if (mapPointsBuilder_ == null) {
          ensureMapPointsIsMutable();
          mapPoints_.add(index, builderForValue.build());
          onChanged();
        } else {
          mapPointsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
       */
      public Builder addAllMapPoints(
          java.lang.Iterable<? extends cn.chennan.server.proto.Http.Point3f> values) {
        if (mapPointsBuilder_ == null) {
          ensureMapPointsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, mapPoints_);
          onChanged();
        } else {
          mapPointsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
       */
      public Builder clearMapPoints() {
        if (mapPointsBuilder_ == null) {
          mapPoints_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          mapPointsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
       */
      public Builder removeMapPoints(int index) {
        if (mapPointsBuilder_ == null) {
          ensureMapPointsIsMutable();
          mapPoints_.remove(index);
          onChanged();
        } else {
          mapPointsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
       */
      public cn.chennan.server.proto.Http.Point3f.Builder getMapPointsBuilder(
          int index) {
        return getMapPointsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
       */
      public cn.chennan.server.proto.Http.Point3fOrBuilder getMapPointsOrBuilder(
          int index) {
        if (mapPointsBuilder_ == null) {
          return mapPoints_.get(index);  } else {
          return mapPointsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
       */
      public java.util.List<? extends cn.chennan.server.proto.Http.Point3fOrBuilder> 
           getMapPointsOrBuilderList() {
        if (mapPointsBuilder_ != null) {
          return mapPointsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(mapPoints_);
        }
      }
      /**
       * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
       */
      public cn.chennan.server.proto.Http.Point3f.Builder addMapPointsBuilder() {
        return getMapPointsFieldBuilder().addBuilder(
            cn.chennan.server.proto.Http.Point3f.getDefaultInstance());
      }
      /**
       * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
       */
      public cn.chennan.server.proto.Http.Point3f.Builder addMapPointsBuilder(
          int index) {
        return getMapPointsFieldBuilder().addBuilder(
            index, cn.chennan.server.proto.Http.Point3f.getDefaultInstance());
      }
      /**
       * <code>repeated .cn.chennan.server.proto.Point3f map_points = 2;</code>
       */
      public java.util.List<cn.chennan.server.proto.Http.Point3f.Builder> 
           getMapPointsBuilderList() {
        return getMapPointsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.chennan.server.proto.Http.Point3f, cn.chennan.server.proto.Http.Point3f.Builder, cn.chennan.server.proto.Http.Point3fOrBuilder> 
          getMapPointsFieldBuilder() {
        if (mapPointsBuilder_ == null) {
          mapPointsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cn.chennan.server.proto.Http.Point3f, cn.chennan.server.proto.Http.Point3f.Builder, cn.chennan.server.proto.Http.Point3fOrBuilder>(
                  mapPoints_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          mapPoints_ = null;
        }
        return mapPointsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.chennan.server.proto.PointCloud)
    }

    // @@protoc_insertion_point(class_scope:cn.chennan.server.proto.PointCloud)
    private static final cn.chennan.server.proto.Http.PointCloud DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.chennan.server.proto.Http.PointCloud();
    }

    public static cn.chennan.server.proto.Http.PointCloud getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PointCloud>
        PARSER = new com.google.protobuf.AbstractParser<PointCloud>() {
      @java.lang.Override
      public PointCloud parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PointCloud(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PointCloud> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PointCloud> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.chennan.server.proto.Http.PointCloud getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_chennan_server_proto_Point3f_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_chennan_server_proto_Point3f_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_chennan_server_proto_PointCloud_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_chennan_server_proto_PointCloud_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nhttp.proto\022\027cn.chennan.server.proto\"*\n" +
      "\007Point3f\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(" +
      "\002\"Q\n\nPointCloud\022\r\n\005total\030\001 \001(\005\0224\n\nmap_po" +
      "ints\030\002 \003(\0132 .cn.chennan.server.proto.Poi" +
      "nt3fb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_chennan_server_proto_Point3f_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_chennan_server_proto_Point3f_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_chennan_server_proto_Point3f_descriptor,
        new java.lang.String[] { "X", "Y", "Z", });
    internal_static_cn_chennan_server_proto_PointCloud_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_chennan_server_proto_PointCloud_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_chennan_server_proto_PointCloud_descriptor,
        new java.lang.String[] { "Total", "MapPoints", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
